import React from 'react';
import LegalPageLayout from '@/components/layout/LegalPageLayout';
import LegalSection from '@/components/ui/LegalSection';

/**
 * Terms of Service for Cora AI — an open-source, self-hosted application.
 *
 * These terms reflect the self-hosted model: the operator deploys and controls
 * the instance, and users interact with that specific deployment.
 */
const TermsOfServicePage: React.FC = () => {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="July 2026">

      <LegalSection title="Introduction" number={1}>
        <p>
          Welcome to Cora AI, an open-source educational AI assistant for the Voluntary Carbon
          Market (VCM). Cora AI is self-hosted software released under the Apache License 2.0. By
          accessing or using a Cora AI instance, you agree to be bound by these Terms of Service.
          Cora AI is designed to educate users about methodologies, projects, and complex topics
          related to carbon markets through interactive AI-powered conversations and comprehensive
          educational resources.
        </p>
      </LegalSection>

      <LegalSection title="Open Source License" number={2}>
        <p>
          Cora AI is licensed under the Apache License 2.0. You are free to use, modify, and
          distribute the software in accordance with the terms of that license. The operator of the
          instance you are using may have modified the software; the project maintainers are not
          responsible for modified deployments.
        </p>
      </LegalSection>

      <LegalSection title="Research and Educational Tool" number={3}>
        <p>
          This service is provided as a research and educational tool. The AI-powered features may
          produce inaccurate, incomplete, or inappropriate responses. You should not rely solely on
          the information provided for making financial, legal, or business decisions. Always
          verify critical information against primary sources.
        </p>
        <p>
          No warranties are made about the accuracy, completeness, or reliability of the information
          provided through this platform.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable Use" number={4}>
        <p>You agree not to use this service for:</p>
        <ul>
          <li>Any illegal, harmful, violent, racist, sexual, or other offensive purposes</li>
          <li>Sharing personal, sensitive, or confidential information of others without consent</li>
          <li>Uploading content that is illegal, including child sexual abuse material, content that
            promotes terrorism, or content that infringes on intellectual property rights</li>
          <li>Attempting to manipulate, exploit, or attack the AI systems or underlying
            infrastructure</li>
          <li>Any activity that could harm the service, the operator, or other users</li>
          <li>Automated bulk queries that degrade service quality for other users</li>
        </ul>
      </LegalSection>

      <LegalSection title="Content Responsibility" number={5}>
        <p>
          Cora AI allows users to upload documents and generate AI responses based on those
          documents. The following principles apply:
        </p>
        <ul>
          <li><strong>Uploaded content:</strong> Users are responsible for ensuring they have the
            right to upload and process any documents they submit. Do not upload copyrighted
            material without permission, or content that violates applicable laws.</li>
          <li><strong>AI-generated content:</strong> Responses generated by the AI are based on
            retrieved documents and model inference. They may contain errors or reflect biases
            present in the source material. Users should critically evaluate all responses.</li>
          <li><strong>Content moderation:</strong> The operator is responsible for reviewing
            uploaded content and removing any inappropriate or illegal material. The project
            includes PII redaction by default, but does not automatically detect illegal content.
            See the project's content moderation guidelines for details.</li>
          <li><strong>Reporting:</strong> If you encounter inappropriate or illegal content on a
            Cora AI instance, report it to the operator of that instance.</li>
        </ul>
      </LegalSection>

      <LegalSection title="Data Handling" number={6}>
        <p>
          Cora AI follows a local-first data model. Your chat history and conversations are stored
          on the machine where the instance is deployed, not in any central cloud service. PII is
          automatically redacted before storage. No user accounts are required, and no personal
          identifiers such as IP addresses are collected by the application.
        </p>
        <p>
          If the operator has configured external API providers (e.g. for AI inference or web
          search), some data may be sent to those providers. See the Privacy Policy for details.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of Liability" number={7}>
        <p>
          This service is provided "as is" and "as available" without warranties of any kind, either
          express or implied. The project maintainers and contributors shall not be liable for any
          damages arising from the use of this software, including but not limited to direct,
          indirect, incidental, special, or consequential damages.
        </p>
        <p>
          The operator of a specific Cora AI instance may have separate terms or liabilities
          applicable to their deployment.
        </p>
      </LegalSection>

      <LegalSection title="Modifications" number={8}>
        <p>
          These Terms of Service may be updated as the project evolves. Changes will be posted in
          the project repository. Operators are encouraged to review the terms periodically and
          inform their users of any material changes.
        </p>
      </LegalSection>

      <LegalSection title="Contact" number={9}>
        <p>
          If you have questions about these Terms of Service, please contact the operator of the
          Cora AI instance you are using. For questions about the project itself, refer to the
          project repository or the contact information provided in the README.
        </p>
      </LegalSection>

    </LegalPageLayout>
  );
};

export default TermsOfServicePage;
